# Generated by Django 5.2 on 2025-05-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='source',
        ),
        migrations.RemoveField(
            model_name='price',
            name='symbol',
        ),
        migrations.AddField(
            model_name='price',
            name='asset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
